# AnyNote Stack
# Self-hosted note-taking application
# Deploy with: docker stack deploy -c stacks/productivity/media.docker-compose.yml productivity

version: '3.8'

services:
  anynote:
    image: ghcr.io/anyproto/anynote-heart:latest
    hostname: anynote
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gpu == true
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      restart_policy:
        condition: any
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - anynote-data:/data
    networks:
      - homelab-net
    ports:
      - target: 8080
        published: 3030
        protocol: tcp
        mode: host

networks:
  homelab-net:
    external: true
    name: homelab-net

volumes:
  anynote-data:
    driver: local
    name: anynote-data
