# Proxy Stack
# Nginx Proxy Manager for HTTPS termination and reverse proxy
# Deploy with: docker stack deploy -c stacks/proxy/media.docker-compose.yml proxy

version: '3.8'

services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    hostname: nginx-proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.proxy == true
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - nginx-proxy-data:/data
      - nginx-proxy-letsencrypt:/etc/letsencrypt
    networks:
      - homelab-net
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 81
        published: 81
        protocol: tcp
        mode: host

networks:
  homelab-net:
    external: true
    name: homelab-net

volumes:
  nginx-proxy-data:
    external: true
    name: nginx-proxy-data

  nginx-proxy-letsencrypt:
    driver: local
    name: nginx-proxy-letsencrypt
