# ARR Stack
# Automated media download management (Sonarr, Radarr, Transmission)
# Deploy with: docker stack deploy -c stacks/arr-stack/media.docker-compose.yml arr-stack

version: '3.8'

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    hostname: sonarr
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.arr == true
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr-config:/config
      - /media/series:/media/series
      - /media/movies:/media/movies
      - /media/incomplete:/downloads
    networks:
      - homelab-net
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    hostname: radarr
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.arr == true
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - radarr-config:/config
      - /media/movies:/media/movies
      - /media/incomplete:/downloads
    networks:
      - homelab-net
    ports:
      - target: 7878
        published: 7878
        protocol: tcp
        mode: host

  transmission:
    image: lscr.io/linuxserver/qbittorrent:latest
    hostname: transmission
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.arr == true
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=911
      - PGID=911
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=9091
      - UMASK=000
    volumes:
      - transmission-config:/config
      - /media/incomplete:/downloads
      - /media/audiobooks:/audiobooks
      - transmission-watch:/watch
    networks:
      - homelab-net
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
        mode: host
      - target: 6881
        published: 6881
        protocol: tcp
        mode: host
      - target: 6881
        published: 6881
        protocol: udp
        mode: host

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    hostname: bazarr
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.arr == true
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - bazarr-config:/config
      - /media/series:/media/series
      - /media/movies:/media/movies
    networks:
      - homelab-net
    ports:
      - target: 6767
        published: 6767
        protocol: tcp
        mode: host

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    hostname: jackett
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.arr == true
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - jackett-config:/config
      - /media/incomplete:/downloads
    networks:
      - homelab-net
    ports:
      - target: 9117
        published: 9117
        protocol: tcp
        mode: host

networks:
  homelab-net:
    external: true
    name: homelab-net

volumes:
  sonarr-config:
    external: true
    name: sonarr-config

  radarr-config:
    external: true
    name: radarr-config

  transmission-config:
    external: true
    name: transmission-config

  transmission-watch:
    driver: local
    name: transmission-watch

  bazarr-config:
    external: true
    name: bazarr-config

  jackett-config:
    external: true
    name: jackett-config
