# Listenarr Stack
# Audiobook collection manager - similar to Sonarr/Radarr for audiobooks
# Deploy with: docker stack deploy -c stacks/listenarr-stack/media.docker-compose.yml listenarr
#
# Features:
# - Search, download, and organize audiobooks automatically
# - Metadata from Audible and Amazon
# - Supports: MP3, M4A, M4B, FLAC, AAC, OGG, OPUS
# - Integrates with Jackett, qBittorrent, Transmission, SABnzbd, NZBGet

version: '3.8'

services:
  listenarr:
    image: ghcr.io/therobbiedavis/listenarr:canary
    hostname: listenarr
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pop-os
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      restart_policy:
        condition: any
    environment:
      - LISTENARR_PUBLIC_URL=http://listenarr.homelab
      - TZ=America/Sao_Paulo
    volumes:
      - /data/docker/listenarr:/app/config
      - /media/downloads:/downloads
      - /media/audiobooks:/audiobooks
    networks:
      - homelab-net
    ports:
      - target: 5000
        published: 8988
        protocol: tcp
        mode: host

networks:
  homelab-net:
    external: true
    name: homelab-net
